### ISSUE TITLE
Not working on NodeJS 22

### ISSUE THREAD

**Issue by WieFel** [matfantinel/image-transmutation#3] opened 2024-10-20 10:12 UTC
Hi @matfantinel,

I am using your svelte template and trying to build it, but get the following error on build:
```
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at $o (/Users/felix/Projects/wiefel.dev/node_modules/esm/esm.js:1:224377)
    at wu (/Users/felix/Projects/wiefel.dev/node_modules/esm/esm.js:1:227324)
    at Eu (/Users/felix/Projects/wiefel.dev/node_modules/esm/esm.js:1:227999)
    at Module.<anonymous> (/Users/felix/Projects/wiefel.dev/node_modules/esm/esm.js:1:295976)
    at n (/Users/felix/Projects/wiefel.dev/node_modules/esm/esm.js:1:279589)
    at Object.<anonymous> (/Users/felix/Projects/wiefel.dev/node_modules/image-transmutation/bin/image-transmutation:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)
    at Module._load (node:internal/modules/cjs/loader:1127:12)
```

It seems to be related to this package, that's why I open the issue here. Do you know how to resolve this?

**Comment by matfantinel** [comment] 2024-10-20 20:01
Hi @WieFel ! What version of NodeJS are you using? I was able to clone the template (and your repo) and run `npm install` and `npm build` without errors, on Node 18.20.3.

**Comment by WieFel** [comment] 2024-10-21 20:25
I'm on Node `v22.6.0`. Could that be too new?

**Comment by matfantinel** [comment] 2024-10-21 20:38
@WieFel I tested with NodeJS 18, 20 and 22 locally, and indeed it seems to be broken on NodeJS 22, though I got a different, kinda unreadable, error stacktrace:

(you can just run `npm run optimize-images` to reproduce it:

```shell
➜ npm run optimize-images

> sveltekit-static-blog-template@1.0.0 optimize-images
> image-transmutation --run --sourceFolder './build/images' --targetFolder './build/images' --inputFormats 'jpg' --inputFormats 'jpeg' --inputFormats 'png' --outputFormats 'png' --outputFormats 'webp' --outputFormats 'avif'


  #  node[39940]: void node::fs::InternalModuleStat(const FunctionCallbackInfo<v8::Value> &) at ../src/node_file.cc:1037
  #  Assertion failed: (args.Length()) >= (2)

----- Native stack trace -----

 1: 0x102eef754 node::Assert(node::AssertionInfo const&) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
 2: 0x104afed80 node::fs::InternalModuleStat(v8::FunctionCallbackInfo<v8::Value> const&) (.cold.3) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
 3: 0x102f0389c node::fs::InternalModuleStat(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
 4: 0x103acaf98 Builtins_CallApiCallbackGeneric [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
 5: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
 6: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
 7: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
 8: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
 9: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
10: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
11: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
12: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
13: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
14: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
15: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
16: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
17: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
18: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
19: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
20: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
21: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
22: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
23: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
24: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
25: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
26: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
27: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
28: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
29: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
30: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
31: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
32: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
33: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
34: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
35: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
36: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
37: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
38: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
39: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
40: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
41: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
42: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
43: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
44: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
45: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
46: 0x103ac8ef0 Builtins_InterpreterEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
47: 0x103ac6c0c Builtins_JSEntryTrampoline [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
48: 0x103ac68f4 Builtins_JSEntry [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
49: 0x10325ec08 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
50: 0x10325e54c v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
51: 0x10312f36c v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
52: 0x102ecb7d8 node::builtins::BuiltinLoader::CompileAndCall(v8::Local<v8::Context>, char const*, node::Realm*) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
53: 0x102f798ec node::Realm::ExecuteBootstrapper(char const*) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
54: 0x102ea9c60 node::StartExecution(node::Environment*, char const*) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
55: 0x102ea9b80 node::StartExecution(node::Environment*, std::__1::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
56: 0x102e12460 node::LoadEnvironment(node::Environment*, std::__1::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>, std::__1::function<void (node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Value>)>) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
57: 0x102f39c74 node::NodeMainInstance::Run(node::ExitCode*, node::Environment*) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
58: 0x102f39a6c node::NodeMainInstance::Run() [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
59: 0x102ead59c node::Start(int, char**) [/Users/matt/.nvm/versions/node/v22.10.0/bin/node]
60: 0x192cb4274 start [/usr/lib/dyld]

----- JavaScript stack trace -----

1: /Users/matt/Projetos/temp/wiefel.dev/node_modules/esm/esm.js:1:34535
2: /Users/matt/Projetos/temp/wiefel.dev/node_modules/esm/esm.js:1:34176
3: /Users/matt/Projetos/temp/wiefel.dev/node_modules/esm/esm.js:1:34506
4: /Users/matt/Projetos/temp/wiefel.dev/node_modules/esm/esm.js:1:173374
5: /Users/matt/Projetos/temp/wiefel.dev/node_modules/esm/esm.js:1:173420
6: /Users/matt/Projetos/temp/wiefel.dev/node_modules/esm/esm.js:1:173521
7: /Users/matt/Projetos/temp/wiefel.dev/node_modules/esm/esm.js:1:258942
8: /Users/matt/Projetos/temp/wiefel.dev/node_modules/esm/esm.js:1:261569
9: e (/Users/matt/Projetos/temp/wiefel.dev/node_modules/esm/esm.js:1:262673)
10: get (/Users/matt/Projetos/temp/wiefel.dev/node_modules/esm/esm.js:1:262740)


[1]    39921 abort      npm run optimize-images
```

**Comment by matfantinel** [comment] 2024-10-21 20:41
@WieFel while this isn't fixed, you can try working with NodeJS 20 instead. Should be really easy to swap between NodeJS versions if you use something like [nvm](https://github.com/nvm-sh/nvm).

**Comment by WieFel** [comment] 2024-10-21 21:00
Yes with 20 it works! Thank you so much 😊
And by the way, thanks for the cool template, I love it already!

**Comment by matfantinel** [comment] 2024-10-21 21:04
@WieFel actually, I think I found a fix for it. I haven't merged it yet because I need to properly test it on older NodeJS versions still.

But for your project, if you wanna continue to use NodeJS 22, you can run:

`npm install --save-dev image-transmutation@matfantinel/image-transmutation#node22`

This will install this package with the latest changes from this branch: https://github.com/matfantinel/image-transmutation/pull/4

Once it's merged, I'll let you know so you can update it to the new version !

**Comment by WieFel** [comment] 2024-10-21 21:09
@matfantinel thanks for the quick fix! Anyway it's not so urgent. Take your time!

**Closed as completed** 2024-10-21 21:12 UTC

**Comment by matfantinel** [comment] 2024-10-21 21:17
@WieFel hah, it was actually much easier than I thought so I just published a new version to npm 😉

You can install latest version with `npm install --save-dev image-transmutation@latest`. I'll update the template accordingly.
